feat: Add process to replace with template files.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,6 +21,7 @@ jobs:
           email: "39184410+ryohidaka@users.noreply.github.com"
           remove-license: true
           excluded: "test/excluded-dir, test/excluded-file.txt"
+          template-dir: ".github/template"
 
       - name: Install jq
         run: sudo apt-get install jq
@@ -44,5 +45,12 @@ jobs:
         run: |
           if [ -d "test/excluded-dir" ] || [ -f "test/excluded-file.txt" ]; then
             echo "::error:: Excluded paths found!"
+            exit 1
+          fi
+
+      - name: Check for template is copied
+        run: |
+          if [ ! -d "test-dir" ] || [ ! -f "test-file.txt" ]; then
+            echo "::error:: Required paths not found!"
             exit 1
           fi
