feat: Add process to replace package.json params.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,3 +15,20 @@ jobs:
       - uses: actions/checkout@v4
 
       - uses: ./
+        with:
+          description: "hogehoge"
+          version: "0.1.0"
+          email: "39184410+ryohidaka@users.noreply.github.com"
+          remove-license: true
+
+      - name: Install jq
+        run: sudo apt-get install jq
+        shell: bash
+
+      - name: Check package.json
+        run: |
+          DESCRIPTION=$(jq -r .description package.json)
+          if [ "$DESCRIPTION" != "hogehoge" ]; then
+            echo "::error:: Description in package.json is not 'hogehoge'. It is '$DESCRIPTION'."
+            exit 1
+          fi
